baseurl = "/"
MetaDataFormat = "yaml"
contentdir = "content"
layoutdir = "layouts"
publishdir = "../public"
title = "sircus"
copyright = "Copyright (c) 2015 blivesta and ungki. all rights reserved."

[params]
  description = "The scalable css for responsive project."
  author = "blivesta"
  maintainer = "ungki"
  tags = "css3, sircus, rem, calc"
  sircus_url = "http://sircus.blivesta.com"
  github_url = "https://github.com/sircus/sircus"
  twitter = "blivesta"
  git_fork_btn = "http://ghbtns.com/github-btn.html?user=sircus&amp;repo=sircus&amp;type=fork&amp;count=true"
  git_star_btn = "http://ghbtns.com/github-btn.html?user=sircus&amp;repo=sircus&amp;type=watch&amp;count=true"
