name = "kicss"
description = "The scalable css for responsive project."
source_repo = "https://github.com/kicss/kicss"
tags = ["kicss", "css"]
features = ["css"]
license = "MIT"

[author]
    name = "blivesta"
    homepage = "http://blivesta.com"

[maintainer]
    name = "ungki"
    homepage = "http://markquery.com"
